### ISSUE TITLE
implement CmdUpdateRepo

### ISSUE THREAD

**Issue by julieqiu** [googleapis/generator#27] opened 2024-12-11 13:14 UTC
We need the "copy back" code in here: copying from the output directory back into the repo. (Ideally failing if we find any file that already exists in the repo - "clean" should have removed everything.)

_Originally posted by @jskeet in https://github.com/googleapis/generator/pull/25#discussion_r1879642845_

**Comment by jskeet** [comment] 2024-12-11 17:16
To clarify, the steps are:

- Clone a repo (or use a local repo)
- Run the "generate" command to generate into an empty output directory
- Run the "clean" command to remove all relevant generated files from the repo directory
- Copy the newly-generated code from the output directory into the repo directory (assuming that root-of-output maps to root-of-repo)
  - For bonus points, fail if the file we're copying from output already exists in the repo, as that means the clean hasn't worked fully
- Then we can build, commit etc

**Comment by jskeet** [comment] 2024-12-12 11:02
#32 is effectively a duplicate of this with more details, so I might as well close this one.

**Closed by jskeet** 2024-12-12 11:02 UTC
